## Pandas - Importing data

Please download from Google Drive <a href="https://drive.google.com/file/d/1lN5Eh2wz_DDOlcI7as9gQcmUALNqs0_y/view?usp=share_link">this data</a>.

In [1]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

- ```ems_2019_first_6_months.csv``` into a dataframe named ```ems_19_first_df```

In [2]:
## import data and store in dataframe
ems_19_first_df = pd.read_csv("wk4-hw-data/ems_2019_first_6_months.csv")

In [3]:
## call the first 10 rows
ems_19_first_df.head(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,190010111,2019-01-01 00:24:51,SICK,6,SICK,6,01/01/2019 12:25:28 AM,Y,37,01/01/2019 12:25:56 AM,...,9.0,2.0,103.0,1.0,12.0,N,N,N,N,chunk10.csv
1,190010112,2019-01-01 00:25:22,DRUG,4,DRUG,4,01/01/2019 12:25:39 AM,Y,17,01/01/2019 12:26:03 AM,...,23.0,9.0,111.0,4.0,13.0,N,N,N,N,chunk10.csv
2,190010113,2019-01-01 00:25:52,DRUG,4,DRUG,4,01/01/2019 12:25:57 AM,Y,5,01/01/2019 12:26:11 AM,...,63.0,45.0,318.0,22.0,8.0,N,N,N,N,chunk13.csv
3,190010114,2019-01-01 00:25:52,OBMAJ,3,OBMAJ,3,01/01/2019 12:26:13 AM,Y,21,01/01/2019 12:26:24 AM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk14.csv
4,190010115,2019-01-01 00:26:03,EDP,7,EDP,7,01/01/2019 12:26:12 AM,Y,9,01/01/2019 12:26:29 AM,...,101.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk14.csv
5,190073272,2019-01-07 17:49:43,EDP,7,EDP,7,01/07/2019 05:49:50 PM,Y,7,01/07/2019 05:50:04 PM,...,17.0,5.0,106.0,2.0,12.0,N,N,N,N,chunk149.csv
6,190073416,2019-01-07 18:27:54,EDP,7,EDP,7,01/07/2019 06:28:33 PM,Y,39,01/07/2019 06:28:44 PM,...,6.0,3.0,102.0,2.0,10.0,N,N,N,N,chunk149.csv
7,190081434,2019-01-08 10:28:31,UNKNOW,4,UNKNOW,4,01/08/2019 10:29:19 AM,Y,48,01/08/2019 10:29:36 AM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk149.csv
8,190081743,2019-01-08 11:43:35,UNKNOW,4,UNKNOW,4,01/08/2019 11:43:47 AM,Y,12,01/08/2019 11:43:55 AM,...,7.0,1.0,103.0,2.0,12.0,N,N,N,N,chunk149.csv
9,190081744,2019-01-08 11:43:48,EDP,7,EDP,7,01/08/2019 11:43:59 AM,Y,11,01/08/2019 11:44:30 AM,...,44.0,16.0,204.0,9.0,15.0,N,N,N,N,chunk149.csv

In [4]:
## call the last 5 rows
ems_19_first_df.tail()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
754651,190010106,2019-01-01 00:24:12,DRUG,4,DRUG,4,01/01/2019 12:28:52 AM,Y,280,01/01/2019 12:28:52 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754652,190010107,2019-01-01 00:24:14,UNC,2,UNC,2,01/01/2019 12:24:38 AM,Y,24,01/01/2019 12:24:57 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754653,190010108,2019-01-01 00:24:16,INJMAJ,3,INJMAJ,3,01/01/2019 12:25:50 AM,Y,94,01/01/2019 12:25:50 AM,...,18.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754654,190010109,2019-01-01 00:24:23,CARD,3,CARD,3,01/01/2019 12:25:08 AM,Y,45,01/01/2019 12:25:27 AM,...,50.0,14.0,208.0,10.0,13.0,N,N,N,N,chunk82.csv
754655,190010110,2019-01-01 00:24:35,DRUG,4,DRUG,4,01/01/2019 12:25:28 AM,Y,53,01/01/2019 12:25:40 AM,...,62.0,47.0,311.0,20.0,10.0,N,N,N,N,chunk82.csv

In [5]:
## call a 20 random rows
ems_19_first_df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
529627,191332569,2019-05-13 14:53:56,ABDPN,5,ABDPN,5,05/13/2019 03:12:42 PM,Y,1126,05/13/2019 03:13:00 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk155.csv
713313,191751961,2019-06-24 11:21:01,MVAINJ,4,MVAINJ,4,06/24/2019 11:23:03 AM,Y,122,06/24/2019 11:23:23 AM,...,45.0,12.0,210.0,11.0,16.0,N,N,N,N,chunk157.csv
304704,190790147,2019-03-20 01:02:02,INJURY,5,INJURY,5,03/20/2019 01:02:09 AM,Y,7,03/20/2019 01:02:18 AM,...,104.0,30.0,405.0,24.0,6.0,N,N,N,N,chunk152.csv
584567,191460075,2019-05-26 00:19:31,EDP,7,EDP,7,05/26/2019 12:19:54 AM,Y,23,05/26/2019 12:20:17 AM,...,6.0,3.0,102.0,2.0,10.0,N,N,N,N,chunk155.csv
201101,190531475,2019-02-22 11:00:11,SICK,6,SICK,6,02/22/2019 11:00:16 AM,Y,5,02/22/2019 11:00:32 AM,...,62.0,47.0,311.0,20.0,10.0,N,N,N,N,chunk151.csv
98628,190280035,2019-01-28 00:14:48,ABDPN,5,ABDPN,5,01/28/2019 12:16:06 AM,Y,78,01/28/2019 12:16:16 AM,...,46.0,14.0,205.0,9.0,15.0,N,N,N,N,chunk150.csv
495249,191251930,2019-05-05 12:09:01,EDP,7,EDP,7,05/05/2019 12:09:17 PM,Y,16,05/05/2019 12:09:36 PM,...,5.0,1.0,102.0,2.0,10.0,N,N,N,N,chunk154.csv
272012,190710937,2019-03-12 08:32:15,CARD,3,CARD,3,03/12/2019 08:32:29 AM,Y,14,03/12/2019 08:32:38 AM,...,122.0,50.0,502.0,31.0,11.0,N,N,N,N,chunk152.csv
536921,191351495,2019-05-15 10:50:32,CARD,3,CARD,3,05/15/2019 10:50:49 AM,Y,17,05/15/2019 10:51:34 AM,...,102.0,29.0,409.0,28.0,5.0,N,N,N,N,chunk155.csv
295254,190763167,2019-03-17 19:03:11,ASTHMB,3,SICK,6,03/17/2019 07:03:53 PM,Y,42,03/17/2019 07:04:12 PM,...,42.0,17.0,203.0,12.0,15.0,N,N,N,N,chunk152.csv
459673,191162827,2019-04-26 17:03:51,EDPC,5,EDPC,5,04/26/2019 05:04:04 PM,Y,13,04/26/2019 05:04:17 PM,...,77.0,41.0,308.0,17.0,9.0,N,N,N,N,chunk154.csv
136518,190370781,2019-02-06 06:58:59,CARDBR,2,CARDBR,2,02/06/2019 06:59:09 AM,Y,10,02/06/2019 07:00:24 AM,...,44.0,17.0,204.0,9.0,15.0,N,N,N,N,chunk151.csv
286149,190742805,2019-03-15 15:29:02,UNC,2,UNC,2,03/15/2019 03:29:27 PM,Y,25,03/15/2019 03:29:38 PM,...,47.0,12.0,212.0,11.0,16.0,N,N,N,N,chunk152.csv
34214,190113472,2019-01-11 18:59:27,COLD,5,COLD,5,01/11/2019 06:59:59 PM,Y,32,01/11/2019 07:00:39 PM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk150.csv
413689,191051732,2019-04-15 11:06:57,SICMIN,7,SICMIN,7,04/15/2019 11:07:29 AM,Y,32,04/15/2019 11:07:41 AM,...,14.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk154.csv
143026,190383075,2019-02-07 16:59:31,INJURY,5,INJURY,5,02/07/2019 05:18:23 PM,Y,1132,02/07/2019 05:19:27 PM,...,13.0,2.0,106.0,2.0,12.0,N,N,N,N,chunk151.csv
333095,190860398,2019-03-27 02:39:18,ABDPN,5,ABDPN,5,03/27/2019 02:39:18 AM,Y,0,03/27/2019 02:39:18 AM,...,5.0,1.0,103.0,2.0,7.0,N,N,N,N,chunk153.csv
652084,191611902,2019-06-10 12:11:18,DIFFBR,2,DIFFBR,2,06/10/2019 12:11:34 PM,Y,16,06/10/2019 12:11:45 PM,...,46.0,14.0,205.0,10.0,15.0,N,N,N,N,chunk156.csv
621040,191541952,2019-06-03 12:31:16,MVAINJ,4,MVAINJ,4,06/03/2019 12:32:51 PM,Y,95,06/03/2019 12:33:05 PM,...,24.0,7.0,107.0,3.0,13.0,N,N,N,N,chunk156.csv
498941,191261679,2019-05-06 11:05:29,UNC,2,UNC,2,05/06/2019 11:05:47 AM,Y,18,05/06/2019 11:05:55 AM,...,32.0,9.0,110.0,5.0,13.0,N,N,N,N,chunk154.csv

In [6]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there?
ems_19_first_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 754656 entries, 0 to 754655
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   CAD_INCIDENT_ID                 754656 non-null  int64
 1   INCIDENT_DATETIME               754656 non-null  object
 2   INITIAL_CALL_TYPE               754656 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     754656 non-null  int64
 4   FINAL_CALL_TYPE                 754656 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       754656 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       749544 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  754656 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    754656 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       748561 non-null  object
 10  FIRST_ON_SCENE_DATETIME         729221 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  754656 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    729068 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   729221 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          522462 non-null  object
 15  FIRST_HOSP_ARRIVAL_DATETIME     518867 non-null  object
 16  INCIDENT_CLOSE_DATETIME         754540 non-null  object
 17  HELD_INDICATOR                  754656 non-null  object
 18  INCIDENT_DISPOSITION_CODE       748265 non-null  float64
 19  BOROUGH                         754656 non-null  object
 20  INCIDENT_DISPATCH_AREA          754656 non-null  object
 21  ZIPCODE                         745086 non-null  float64
 22  POLICEPRECINCT                  745102 non-null  float64
 23  CITYCOUNCILDISTRICT             745071 non-null  float64
 24  COMMUNITYDISTRICT               745101 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         744542 non-null  float64
 26  CONGRESSIONALDISTRICT           745071 non-null  float64
 27  REOPEN_INDICATOR                754656 non-null  object
 28  SPECIAL_EVENT_INDICATOR         754656 non-null  object
 29  STANDBY_INDICATOR               754656 non-null  object
 30  TRANSFER_INDICATOR              754656 non-null  object
 31  source                          754656 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 184.2+ MB

### In three separate cells, ingest the 3 other related datasets into this notebook:

- ```ems_2019_last_6_months.csv``` into a dataframe named ```ems_19_last_df```
- ```ems_2020_first_6_months.csv``` into a dataframe named ```ems_20_first_df```
- ```ems_2020_last_6_months.csv``` into a dataframe named ```ems_20_last_df```

We want to combine all 4 dataframes so we can run an analysis on the combined dataframes

In [7]:
### For last 6 months of 2019
## call the dataframe to see what you have
ems_19_last_df = pd.read_csv("wk4-hw-data/ems_2019_last_6_months.csv")
ems_19_last_df

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,191853909,2019-07-04 21:07:53,DRUG,4,DRUG,4,07/04/2019 09:08:16 PM,Y,23,07/04/2019 09:08:26 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
1,191864927,2019-07-05 21:09:53,MVAINJ,4,MVAINJ,4,07/05/2019 09:10:10 PM,Y,17,07/05/2019 09:10:20 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
2,191870823,2019-07-06 05:32:12,INJURY,5,INJURY,5,07/06/2019 05:32:49 AM,Y,37,07/06/2019 05:33:40 AM,...,47.0,12.0,212.0,11.0,16.0,N,N,N,N,chunk157.csv
3,191870824,2019-07-06 05:33:49,UNC,2,UNC,2,07/06/2019 05:33:57 AM,Y,8,07/06/2019 05:34:25 AM,...,32.0,9.0,110.0,5.0,13.0,N,N,N,N,chunk157.csv
4,191870897,2019-07-06 06:20:26,INJURY,5,INJURY,5,07/06/2019 06:20:43 AM,Y,17,07/06/2019 06:20:53 AM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk157.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781735,192702998,2019-09-27 16:20:29,EDP,7,UNKNOW,4,09/27/2019 04:21:09 PM,Y,40,09/27/2019 04:21:21 PM,...,100.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk81.csv
781736,192704269,2019-09-27 21:05:14,OTHER,6,OTHER,6,09/27/2019 09:05:26 PM,Y,12,09/27/2019 09:07:15 PM,...,43.0,18.0,209.0,8.0,15.0,N,N,N,N,chunk81.csv
781737,193012678,2019-10-28 15:01:30,MVAINJ,4,MVAINJ,4,10/28/2019 03:01:30 PM,Y,0,10/28/2019 03:01:30 PM,...,109.0,20.0,407.0,25.0,6.0,N,N,N,N,chunk81.csv
781738,193330212,2019-11-29 01:16:42,EDP,7,EDP,7,11/29/2019 01:17:36 AM,Y,54,11/29/2019 01:17:53 AM,...,28.0,9.0,110.0,5.0,13.0,N,N,N,N,chunk81.csv
781739,193634478,2019-12-29 23:59:34,EDP,7,EDP,7,NaN,N,0,NaN,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk81.csv

In [8]:
### For first 6 months of 2020
## call the dataframe to see what you have
ems_20_first_df = pd.read_csv("wk4-hw-data/ems_2020_first_6_months.csv")
ems_20_first_df

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201012966,2020-04-10 14:36:07,SICK,6,SICK,6,04/10/2020 02:36:37 PM,Y,30,04/10/2020 02:37:36 PM,...,101.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk148.csv
1,201013858,2020-04-10 17:37:57,SICKFC,6,SICKFC,6,04/10/2020 05:56:30 PM,Y,1113,04/10/2020 05:56:30 PM,...,42.0,17.0,203.0,12.0,15.0,N,N,N,N,chunk148.csv
2,201013897,2020-04-10 17:46:07,HYPTN,7,HYPTN,7,04/10/2020 05:51:43 PM,Y,336,04/10/2020 05:51:47 PM,...,62.0,43.0,311.0,20.0,11.0,N,N,N,N,chunk148.csv
3,201014048,2020-04-10 18:19:32,SICKFC,6,SICKFC,6,04/10/2020 06:19:54 PM,Y,22,04/10/2020 06:23:23 PM,...,52.0,14.0,207.0,10.0,13.0,N,N,N,N,chunk148.csv
4,201014049,2020-04-10 18:19:33,INJURY,5,INJURY,5,04/10/2020 06:25:55 PM,Y,382,04/10/2020 06:26:14 PM,...,103.0,27.0,412.0,28.0,5.0,N,N,N,N,chunk148.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741802,201824116,2020-06-30 23:58:45,INJURY,5,INJURY,5,06/30/2020 11:58:56 PM,Y,11,06/30/2020 11:59:18 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk172.csv
741803,201824117,2020-06-30 23:59:00,DRUG,4,DRUG,4,06/30/2020 11:59:24 PM,Y,24,06/30/2020 11:59:40 PM,...,61.0,47.0,315.0,21.0,11.0,N,N,N,N,chunk172.csv
741804,201824118,2020-06-30 23:59:26,INJURY,5,INJURY,5,06/30/2020 11:59:40 PM,Y,14,06/30/2020 11:59:57 PM,...,30.0,7.0,109.0,6.0,13.0,N,N,N,N,chunk172.csv
741805,200293244,2020-01-29 17:15:18,UNKNOW,4,UNKNOW,4,01/29/2020 05:47:34 PM,Y,1936,01/29/2020 05:47:57 PM,...,14.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk81.csv
741806,200293566,2020-01-29 18:32:45,EDPC,7,EDPC,7,NaN,N,0,NaN,...,9.0,2.0,102.0,2.0,12.0,N,N,N,N,chunk81.csv

In [9]:
### For last 6 months of 2020
## call the dataframe to see what you have
ems_20_last_df = pd.read_csv("wk4-hw-data/ems_2020_last_6_months.csv")
ems_20_last_df

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201853344,2020-07-03 19:51:35,MVAINJ,4,MVAINJ,4,07/03/2020 07:52:54 PM,Y,79,07/03/2020 07:53:13 PM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk172.csv
1,201861781,2020-07-04 13:38:45,INJURY,5,INJURY,5,07/04/2020 01:38:55 PM,Y,10,07/04/2020 01:39:01 PM,...,20.0,3.0,107.0,3.0,10.0,N,N,N,N,chunk172.csv
2,201862931,2020-07-04 19:06:08,INJURY,5,INJURY,5,07/04/2020 07:06:34 PM,Y,26,07/04/2020 07:06:53 PM,...,60.0,47.0,313.0,21.0,8.0,N,N,N,N,chunk172.csv
3,201870048,2020-07-05 00:09:31,SICK,6,SICK,6,NaN,N,0,NaN,...,46.0,14.0,205.0,10.0,15.0,N,N,N,N,chunk172.csv
4,201870159,2020-07-05 00:31:24,EDPC,7,SICK,6,NaN,N,0,NaN,...,43.0,17.0,209.0,12.0,15.0,N,N,N,N,chunk172.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670750,203664156,2020-12-31 23:58:15,DIFFBR,2,DIFFBR,2,12/31/2020 11:58:26 PM,Y,11,12/31/2020 11:59:10 PM,...,79.0,36.0,303.0,14.0,7.0,N,N,N,N,chunk214.csv
670751,203664157,2020-12-31 23:58:27,INJURY,5,INJURY,5,12/31/2020 11:59:57 PM,Y,90,01/01/2021 12:01:00 AM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk214.csv
670752,203664158,2020-12-31 23:58:38,CARDBR,2,CARDBR,2,12/31/2020 11:59:32 PM,Y,54,12/31/2020 11:59:40 PM,...,30.0,7.0,109.0,6.0,13.0,N,N,N,N,chunk214.csv
670753,203664159,2020-12-31 23:58:46,MVAINJ,4,MVAINJ,4,12/31/2020 11:59:37 PM,Y,51,01/01/2021 12:01:00 AM,...,48.0,17.0,206.0,12.0,15.0,N,N,N,N,chunk214.csv
670754,203664161,2020-12-31 23:59:13,CARDBR,2,CARDBR,2,01/01/2021 12:00:22 AM,Y,69,01/01/2021 12:01:10 AM,...,77.0,36.0,308.0,16.0,9.0,N,N,N,N,chunk214.csv

## Combine the 4 dataframes

In [10]:
## create a list to combine all 
combine_these_dfs = [ems_19_first_df, ems_19_last_df, ems_20_first_df, ems_20_last_df]

In [11]:
## combine (concat) the dfs
ems_2_yrs= pd.concat(combine_these_dfs)

#### Programmatically (not with a calculator) confirm that their row totals add up to the correct number

In [13]:
## how many rows does the combined df have
ems_2_yrs.shape[0]

2948958

In [14]:
## get total rows when you add up all the individual dataframes

ems_19_first_df.shape[0] + ems_19_last_df.shape[0] + ems_20_first_df.shape[0] + ems_20_last_df.shape[0]

2948958

In [15]:
## add up to total in new df?
ems_2_yrs.shape[0] == ems_19_first_df.shape[0] + ems_19_last_df.shape[0] + ems_20_first_df.shape[0] + ems_20_last_df.shape[0]

True

## Ingest Massive Dataset

Step 1. Open ```global_temps.csv``` in Excel first. What happened?

Step 2. Open this data set in Pandas.

In [16]:
## import global_temps.csv into a df called temps_df

temps_df = pd.read_csv("wk4-hw-data/global_temps.csv")
temps_df.head()

   Region  Country     City  Month  Day  Year  AvgTemperature
0  Africa  Algeria  Algiers      1    1  1995            64.2
1  Africa  Algeria  Algiers      1    2  1995            49.4
2  Africa  Algeria  Algiers      1    3  1995            48.8
3  Africa  Algeria  Algiers      1    4  1995            46.4
4  Africa  Algeria  Algiers      1    5  1995            47.9

## How many rows of data does this dataset have?

In [17]:
## How many rows?
# temps_df.shape ## option 1
temps_df.info() ## option 2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2906327 entries, 0 to 2906326
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   Region          object
 1   Country         object
 2   City            object
 3   Month           int64
 4   Day             int64
 5   Year            int64
 6   AvgTemperature  float64
dtypes: float64(1), int64(3), object(3)
memory usage: 155.2+ MB

## Targeting an Excel sheet

We need the Customs and Border Protection data in this ```multi-data.xlsx``` workbook.

Note that this is an excerpt of the actual CBP data.

In [18]:
### import it here
cbp_df = pd.read_excel("wk4-hw-data/multi-data.xlsx", sheet_name = "CBP", skiprows= 6)

In [19]:
## call the top 15 rows
cbp_df.head(15)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
0,2017-01-20 00:10:00,2017-01-20 10:08:00,9.950000,6-8 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
1,2017-01-20 00:15:00,2017-01-24 17:30:00,113.233333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2,2017-01-20 00:22:00,2017-01-24 17:47:00,113.416667,3-5 years,Female,BRAZIL,SBO,(b)(7)(E ),NaN
3,2017-01-20 00:30:00,2017-01-21 06:35:00,30.083333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
4,2017-01-20 00:30:00,2017-01-21 13:03:00,36.533333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
5,2017-01-20 00:30:00,2017-01-21 15:30:00,38.983333,Under 1 year,Male,HONDURAS,SBO,(b)(7)(E ),NaN
6,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
7,2017-01-20 00:35:00,2017-01-20 15:14:00,14.633333,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
8,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
9,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
10,2017-01-20 00:45:00,2017-01-20 13:15:00,12.500000,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
11,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
12,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
13,2017-01-20 01:20:00,2017-01-24 17:30:00,112.166667,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
14,2017-01-20 01:20:00,2017-01-20 13:40:00,12.333333,9-11 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN