## Pandas - Importing data

Please download from Google Drive <a href="https://drive.google.com/file/d/1lN5Eh2wz_DDOlcI7as9gQcmUALNqs0_y/view?usp=share_link">this data</a>.

In [1]:
## import the pandas library in this cell

import pandas as pd

### Ingest the following dataset into this note:

- ```ems_2019_first_6_months.csv``` into a dataframe named ```ems_19_first_df```

In [10]:
## import data and store in dataframe
pd.read_csv("data_hw_w4/ems_2019_first_6_months.csv")
df = pd.read_csv("data_hw_w4/ems_2019_first_6_months.csv")

In [9]:
## call the first 10 rows
df.head(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,190010111,2019-01-01 00:24:51,SICK,6,SICK,6,01/01/2019 12:25:28 AM,Y,37,01/01/2019 12:25:56 AM,...,9.0,2.0,103.0,1.0,12.0,N,N,N,N,chunk10.csv
1,190010112,2019-01-01 00:25:22,DRUG,4,DRUG,4,01/01/2019 12:25:39 AM,Y,17,01/01/2019 12:26:03 AM,...,23.0,9.0,111.0,4.0,13.0,N,N,N,N,chunk10.csv
2,190010113,2019-01-01 00:25:52,DRUG,4,DRUG,4,01/01/2019 12:25:57 AM,Y,5,01/01/2019 12:26:11 AM,...,63.0,45.0,318.0,22.0,8.0,N,N,N,N,chunk13.csv
3,190010114,2019-01-01 00:25:52,OBMAJ,3,OBMAJ,3,01/01/2019 12:26:13 AM,Y,21,01/01/2019 12:26:24 AM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk14.csv
4,190010115,2019-01-01 00:26:03,EDP,7,EDP,7,01/01/2019 12:26:12 AM,Y,9,01/01/2019 12:26:29 AM,...,101.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk14.csv
5,190073272,2019-01-07 17:49:43,EDP,7,EDP,7,01/07/2019 05:49:50 PM,Y,7,01/07/2019 05:50:04 PM,...,17.0,5.0,106.0,2.0,12.0,N,N,N,N,chunk149.csv
6,190073416,2019-01-07 18:27:54,EDP,7,EDP,7,01/07/2019 06:28:33 PM,Y,39,01/07/2019 06:28:44 PM,...,6.0,3.0,102.0,2.0,10.0,N,N,N,N,chunk149.csv
7,190081434,2019-01-08 10:28:31,UNKNOW,4,UNKNOW,4,01/08/2019 10:29:19 AM,Y,48,01/08/2019 10:29:36 AM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk149.csv
8,190081743,2019-01-08 11:43:35,UNKNOW,4,UNKNOW,4,01/08/2019 11:43:47 AM,Y,12,01/08/2019 11:43:55 AM,...,7.0,1.0,103.0,2.0,12.0,N,N,N,N,chunk149.csv
9,190081744,2019-01-08 11:43:48,EDP,7,EDP,7,01/08/2019 11:43:59 AM,Y,11,01/08/2019 11:44:30 AM,...,44.0,16.0,204.0,9.0,15.0,N,N,N,N,chunk149.csv

In [11]:
## call the last 5 rows
df.tail(5)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
754651,190010106,2019-01-01 00:24:12,DRUG,4,DRUG,4,01/01/2019 12:28:52 AM,Y,280,01/01/2019 12:28:52 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754652,190010107,2019-01-01 00:24:14,UNC,2,UNC,2,01/01/2019 12:24:38 AM,Y,24,01/01/2019 12:24:57 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754653,190010108,2019-01-01 00:24:16,INJMAJ,3,INJMAJ,3,01/01/2019 12:25:50 AM,Y,94,01/01/2019 12:25:50 AM,...,18.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk82.csv
754654,190010109,2019-01-01 00:24:23,CARD,3,CARD,3,01/01/2019 12:25:08 AM,Y,45,01/01/2019 12:25:27 AM,...,50.0,14.0,208.0,10.0,13.0,N,N,N,N,chunk82.csv
754655,190010110,2019-01-01 00:24:35,DRUG,4,DRUG,4,01/01/2019 12:25:28 AM,Y,53,01/01/2019 12:25:40 AM,...,62.0,47.0,311.0,20.0,10.0,N,N,N,N,chunk82.csv

In [6]:
## call a 20 random rows
df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
216339,190571270,2019-02-26 10:04:20,CARD,3,CARD,3,02/26/2019 10:04:41 AM,Y,21,02/26/2019 10:04:59 AM,...,19.0,5.0,108.0,2.0,12.0,N,N,N,N,chunk152.csv
713242,191751885,2019-06-24 11:07:11,SICK,6,SICK,6,06/24/2019 11:07:18 AM,Y,7,06/24/2019 11:08:02 AM,...,108.0,26.0,402.0,30.0,14.0,N,N,N,N,chunk157.csv
404014,191030210,2019-04-13 01:05:20,INJURY,5,INJURY,5,04/13/2019 01:05:31 AM,Y,11,04/13/2019 01:05:59 AM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk153.csv
258904,190674326,2019-03-08 22:20:29,INJMAJ,3,INJMAJ,3,03/08/2019 10:20:40 PM,Y,11,03/08/2019 10:20:45 PM,...,72.0,39.0,307.0,15.0,9.0,N,N,N,N,chunk152.csv
743333,191814275,2019-06-30 20:04:15,INJMAJ,3,INJMAJ,3,06/30/2019 08:04:43 PM,Y,28,06/30/2019 08:04:58 PM,...,70.0,45.0,314.0,22.0,9.0,N,N,N,N,chunk157.csv
486892,191231928,2019-05-03 12:45:10,SICK,6,SICK,6,05/03/2019 12:45:16 PM,Y,6,05/03/2019 12:45:26 PM,...,63.0,46.0,318.0,22.0,8.0,N,N,N,N,chunk154.csv
640454,191583684,2019-06-07 18:07:01,SEIZR,3,SEIZR,3,06/07/2019 06:07:30 PM,Y,29,06/07/2019 06:07:37 PM,...,52.0,14.0,207.0,10.0,13.0,N,N,N,N,chunk156.csv
289955,190751874,2019-03-16 12:27:04,UNC,2,UNC,2,03/16/2019 12:27:18 PM,Y,14,03/16/2019 12:28:00 PM,...,72.0,38.0,307.0,15.0,9.0,N,N,N,N,chunk152.csv
229246,190602512,2019-03-01 15:18:29,DRUG,4,DRUG,4,03/01/2019 03:18:54 PM,Y,25,03/01/2019 03:19:07 PM,...,44.0,14.0,204.0,9.0,15.0,N,N,N,N,chunk152.csv
240058,190631322,2019-03-04 10:15:29,UNKNOW,4,UNKNOW,4,03/04/2019 10:16:01 AM,Y,32,03/04/2019 10:16:42 AM,...,26.0,7.0,109.0,5.0,13.0,N,N,N,N,chunk152.csv
455863,191153098,2019-04-25 17:37:37,CARD,3,CARD,3,04/25/2019 05:37:47 PM,Y,10,04/25/2019 05:37:58 PM,...,44.0,8.0,204.0,7.0,15.0,N,N,N,N,chunk154.csv
432431,191093921,2019-04-19 19:53:48,UNC,2,UNC,2,04/19/2019 07:53:54 PM,Y,6,04/19/2019 07:54:07 PM,...,26.0,9.0,109.0,6.0,13.0,N,N,N,N,chunk154.csv
124972,190342290,2019-02-03 14:36:42,SICK,6,SICK,6,02/03/2019 02:36:59 PM,Y,17,02/03/2019 02:37:07 PM,...,113.0,28.0,412.0,28.0,5.0,N,N,N,N,chunk151.csv
34069,190113309,2019-01-11 18:23:07,INJMAJ,3,INJMAJ,3,01/11/2019 06:23:30 PM,Y,23,01/11/2019 06:23:42 PM,...,60.0,47.0,313.0,21.0,8.0,N,N,N,N,chunk150.csv
245718,190643273,2019-03-05 17:23:52,INJURY,5,INJURY,5,03/05/2019 05:28:26 PM,Y,274,03/05/2019 05:28:39 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk152.csv
663509,191640127,2019-06-13 00:54:18,UNKNOW,4,UNKNOW,4,06/13/2019 12:54:33 AM,Y,15,06/13/2019 12:55:00 AM,...,75.0,37.0,305.0,19.0,7.0,N,N,N,N,chunk156.csv
160636,190430261,2019-02-12 02:20:48,SICMIN,7,SICMIN,7,02/12/2019 02:20:54 AM,Y,6,02/12/2019 02:21:04 AM,...,23.0,8.0,111.0,4.0,13.0,N,N,N,N,chunk151.csv
407493,191034069,2019-04-13 21:26:08,MVAINJ,4,MVAINJ,4,04/13/2019 09:27:49 PM,Y,101,04/13/2019 09:28:11 PM,...,69.0,46.0,318.0,18.0,8.0,N,N,N,N,chunk153.csv
561258,191403900,2019-05-20 18:04:04,DRUG,4,DRUG,4,05/20/2019 06:07:47 PM,Y,223,05/20/2019 06:08:05 PM,...,88.0,35.0,302.0,13.0,8.0,N,N,N,N,chunk155.csv
86195,190243876,2019-01-24 20:08:44,DIFFBR,2,DIFFBR,2,01/24/2019 08:09:04 PM,Y,20,01/24/2019 08:09:19 PM,...,18.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk150.csv

In [13]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 754656 entries, 0 to 754655
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   CAD_INCIDENT_ID                 754656 non-null  int64
 1   INCIDENT_DATETIME               754656 non-null  object
 2   INITIAL_CALL_TYPE               754656 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     754656 non-null  int64
 4   FINAL_CALL_TYPE                 754656 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       754656 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       749544 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  754656 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    754656 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       748561 non-null  object
 10  FIRST_ON_SCENE_DATETIME         729221 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  754656 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    729068 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   729221 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          522462 non-null  object
 15  FIRST_HOSP_ARRIVAL_DATETIME     518867 non-null  object
 16  INCIDENT_CLOSE_DATETIME         754540 non-null  object
 17  HELD_INDICATOR                  754656 non-null  object
 18  INCIDENT_DISPOSITION_CODE       748265 non-null  float64
 19  BOROUGH                         754656 non-null  object
 20  INCIDENT_DISPATCH_AREA          754656 non-null  object
 21  ZIPCODE                         745086 non-null  float64
 22  POLICEPRECINCT                  745102 non-null  float64
 23  CITYCOUNCILDISTRICT             745071 non-null  float64
 24  COMMUNITYDISTRICT               745101 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         744542 non-null  float64
 26  CONGRESSIONALDISTRICT           745071 non-null  float64
 27  REOPEN_INDICATOR                754656 non-null  object
 28  SPECIAL_EVENT_INDICATOR         754656 non-null  object
 29  STANDBY_INDICATOR               754656 non-null  object
 30  TRANSFER_INDICATOR              754656 non-null  object
 31  source                          754656 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 184.2+ MB

### In three separate cells, ingest the 3 other related datasets into this notebook:

- ```ems_2019_last_6_months.csv``` into a dataframe named ```ems_19_last_df```
- ```ems_2020_first_6_months.csv``` into a dataframe named ```ems_20_first_df```
- ```ems_2020_last_6_months.csv``` into a dataframe named ```ems_20_last_df```

We want to combine all 4 dataframes so we can run an analysis on the combined dataframes

In [ ]:
### For last 6 months of 2019
## call the dataframe to see what you have

In [ ]:
### For first 6 months of 2020
## call the dataframe to see what you have

In [ ]:
### For last 6 months of 2020
## call the dataframe to see what you have

## Combine the 4 dataframes

In [ ]:
## create a list to combine all

In [ ]:
## combine (concat) the dfs

#### Programmatically (not with a calculator) confirm that their row totals add up to the correct number

In [ ]:
## how many rows does the combined df have

In [ ]:
## get total rows when you add up all the individual dataframes

## Ingest Massive Dataset

Step 1. Open ```global_temps.csv``` in Excel first. What happened?

Step 2. Open this data set in Pandas.

In [ ]:
## import global_temps.csv into a df called temps_df

## How many rows of data does this dataset have?

In [ ]:
## How many rows?

## Targeting an Excel sheet

We need the Customs and Border Protection data in this ```multi-data.xlsx``` workbook.

Note that this is an excerpt of the actual CBP data.

In [ ]:
### import it here

In [ ]:
## call the top 15 rows